import { Inter } from "next/font/google";
// import "./globals.css";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} style={BodyStyle}>{children}</body>
    </html>
  );
}
const BodyStyle = {
  height: '100%',
  margin: 0,
  padding: 0
}

